# Copyright (c) 2026 Vishal Verma. All rights reserved.
# Type stubs for the native Rust extension module compiled by maturin/PyO3.
# This file enables IDE autocomplete, type checking, and import resolution
# for the compiled `_core.so` / `_core.dylib` native module.
#
# AUTO-GENERATED from runtime introspection of the compiled module.
# To regenerate: `python -c "from state_harness._core import *; ..."`

"""Type stubs for ``state_harness._core`` (Rust/PyO3 native extension)."""

from __future__ import annotations

from typing import Optional


# ─── Exceptions ─────────────────────────────────────────────────────────────

class StabilityViolation(Exception):
    """Raised when ΔV ≥ 0 for `window` consecutive steps."""
    ...

class BudgetExhausted(Exception):
    """Raised when cumulative token spend exceeds the budget ceiling."""
    ...

class PermanentFailure(Exception):
    """Raised on unrecoverable errors (schema violations, invalid configs)."""
    ...


# ─── Stability Status ──────────────────────────────────────────────────────

class StabilityStatus:
    Stable: StabilityStatus
    Warning: StabilityStatus
    Unstable: StabilityStatus
    Tripped: StabilityStatus
    Frozen: StabilityStatus

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


# ─── Telemetry Snapshot ─────────────────────────────────────────────────────

class TelemetrySnapshot:
    step_count: int
    cumulative_tokens: int
    cumulative_errors: int
    energy_trajectory: list[float]
    final_status: StabilityStatus
    consecutive_non_negative: int

    def __repr__(self) -> str: ...


# ─── Lyapunov Monitor ──────────────────────────────────────────────────────

class LyapunovMonitor:
    def __init__(
        self,
        lambda_: float = 1.0,
        window: int = 3,
        budget_ceiling: Optional[int] = None,
    ) -> None: ...

    def record_step(self, tokens_used: int, errors: int) -> StabilityStatus: ...
    def report_transient_failure(self) -> StabilityStatus: ...
    def report_permanent_failure(self, reason: str) -> None: ...
    def check_stability(self) -> StabilityStatus: ...
    def snapshot(self) -> TelemetrySnapshot: ...
    def get_energy_history(self) -> list[float]: ...
    def total_tokens(self) -> int: ...
    def total_steps(self) -> int: ...
    def current_energy(self) -> Optional[float]: ...
    def consecutive_warnings(self) -> int: ...
    def is_tripped(self) -> bool: ...
    def is_frozen(self) -> bool: ...
    def reset(self) -> None: ...


# ─── Monitor Group ─────────────────────────────────────────────────────────

class MonitorGroup:
    def __init__(self, budget_ceiling: Optional[int] = None) -> None: ...

    def add_child(
        self,
        name: str,
        lambda_: float = 1.0,
        window: int = 3,
        budget_ceiling: Optional[int] = None,
    ) -> None: ...
    def remove_child(self, name: str) -> bool: ...
    def record_step(self, name: str, tokens_used: int, errors: int) -> StabilityStatus: ...
    def report_transient(self, name: str) -> StabilityStatus: ...
    def report_permanent(self, name: str, reason: str) -> None: ...
    def aggregate_energy(self) -> dict[str, float]: ...
    def total_energy(self) -> float: ...
    def aggregate_tokens(self) -> int: ...
    def is_all_stable(self) -> bool: ...
    def is_any_tripped(self) -> bool: ...
    def is_any_frozen(self) -> bool: ...
    def child_status(self, name: str) -> StabilityStatus: ...
    def all_statuses(self) -> dict[str, StabilityStatus]: ...
    def aggregate_snapshots(self) -> list[TelemetrySnapshot]: ...
    def child_snapshot(self, name: str) -> TelemetrySnapshot: ...
    def children_names(self) -> list[str]: ...
    def child_count(self) -> int: ...
    def reset_all(self) -> None: ...
    def reset_child(self, name: str) -> None: ...
    def __repr__(self) -> str: ...


# ─── Holographic Engine (VSA) ──────────────────────────────────────────────

class HolographicEngine:
    def __init__(self, dim: int = 10_000) -> None: ...

    def generate_random_vector(self) -> list[int]: ...
    def bind(self, a: list[int], b: list[int]) -> list[int]: ...
    def bundle(self, vectors: list[list[int]]) -> list[int]: ...
    def cosine_similarity(self, a: list[int], b: list[int]) -> float: ...
    def batch_cosine_similarity(
        self, target: list[int], candidates: list[list[int]]
    ) -> list[float]: ...
    def register_invariant(
        self, name: str, key_vector: list[int], value_vector: list[int]
    ) -> None: ...
    def check_drift(self, name: str, context_vector: list[int]) -> float: ...
    def check_all_drift(self, context_vector: list[int]) -> dict[str, float]: ...
    def recover(self, name: str) -> list[int]: ...
    def remove_invariant(self, name: str) -> bool: ...
    def list_invariants(self) -> list[str]: ...
    def invariant_count(self) -> int: ...
    def dimensionality(self) -> int: ...
    def encode_text(self, text: str) -> list[int]: ...
    def batch_encode_texts(self, texts: list[str]) -> list[list[int]]: ...


# ─── RG Decimator ──────────────────────────────────────────────────────────

class ScoredMessage:
    index: int
    score: float
    content: str
    retained: bool

    def __repr__(self) -> str: ...


class RGDecimator:
    def __init__(
        self,
        threshold: float = 0.3,
        max_retained: int = 50,
        structural_keywords: Optional[list[str]] = None,
    ) -> None: ...

    def decimate(self, messages: list[str]) -> list[ScoredMessage]: ...
    def compress(self, messages: list[str]) -> list[str]: ...
    def score_message(
        self, message: str, context: Optional[list[str]] = None
    ) -> float: ...
    def decimate_with_embeddings(
        self, messages: list[str], embeddings: list[list[int]]
    ) -> list[ScoredMessage]: ...
    def get_keywords(self) -> list[str]: ...
    def get_threshold(self) -> float: ...
    def get_max_retained(self) -> int: ...
